image: docker:stable

default:
  tags:
    - docker
    - inside

stages:
  - test
  - attach_report

run-test-job:
    stage: test
    image: python:3.10-slim
    artifacts:
      when: always
      paths:
        - allure_results
      expire_in: 1 day
    services:
      - selenium/standalone-chrome
    script:
      - pip install -r requirements.txt
      - python3 -m pytest --alluredir=allure-result
    allow_failure: true
