image: docker:stable

default:
  tags:
    - docker
    - inside

stages:
  - test

run-test-job:
    stage: test
    image: python:3.10-slim
    script:
      - python --version
      - pip install -r requirements.txt
      - pytest -v
