image: docker:stable

default:
  tags:
    - docker
    - inside

stages:
  - test
  - generate_report

run-test-job:
    stage: test
    image: python:3.10-slim
    artifacts:
      when: always
      paths:
        - allure-result
      expire_in: 1 day
    services:
      - selenium/standalone-chrome
    script:
      - pip install -r requirements.txt
      - python3 -m pytest --alluredir=allure-result
    allow_failure: true

generate_report:
  stage: generate_report
  image: frankescobar/allure-docker-service
  script:
     - allure generate -c allure-result -o allure-report
  artifacts:
    paths:
      - ./allure-result
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always