version: '3.9'

services:
  chrome:
    image: selenium/node-chrome:108.0
    container_name: chrome
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3

  selenium-hub:
    image: selenium/hub:4.7.2
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    depends_on:
      - chrome
    healthcheck:
      test: curl --fail http://localhost:4444 || exit 1
      interval: 5s
      timeout: 5s
      retries: 6

  pytest-runner:
    build:
      context: .
    container_name: pytest-runner
    environment:
      CHROME_HOST: selenium-hub
      CHROME_PORT: 4444
    depends_on:
      selenium-hub:
        condition: service_healthy
    volumes:
      - ./allure-results:/app/allure-results

networks:
  default:
    name: ui.autotest-production
    driver: bridge
